# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setbig.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_Form(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1249, 881)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1231, 861))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(220, 20, 971, 771))
        self.label.setObjectName("label")
        # self.pushButton1= QtWidgets.QPushButton(self.widget)
        # self.pushButton1.setGeometry(QtCore.QRect(900, 130, 75, 23))
        # self.pushButton1.setObjectName("pushButton1")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(90, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(160, 80, 167, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label1 = QtWidgets.QLabel(self.formLayout)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.pushButton1 = QtWidgets.QPushButton(self.formLayout)
        self.pushButton1.setObjectName("pushButton1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton1)
        self.label_2 = QtWidgets.QLabel(self.formLayout)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.formLayout)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "1"))
        self.pushButton.setText(_translate("Form", "还原"))

        self.label1.setText(_translate("Form", "绘制ROI"))
        self.pushButton1.setText(_translate("Form", "重绘"))
        self.label_2.setText(_translate("Form", "恢复至最大画幅"))
        self.pushButton_2.setText(_translate("Form", "执行"))